// ENV
import * as dotenv from "dotenv";
dotenv.config();

// DEPENDENCIES
import playwright from "playwright";
import path from "path";
import fs from "fs";
import { LinkedInScraper } from "./src/scaper/LinkedInScraper.js";

// FILE PATH
const __dirname = import.meta.dirname;
const __cookie_path = path.join(__dirname, "./playwright/.auth/user.json");

// Selectors
const SELECTORS = {
  jobListContainer: ".scaffold-layout__list-container",
  jobListItem: 'li[id^="ember"]',
  jobDetailsContainer:
    ".job-details-jobs-unified-top-card__container--two-pane",
  applyButton: ".jobs-apply-button--top-card",
  filterListItem: 'li[class="search-reusables__filter-value-item"]',
  showAllJobsButton: 'text="Show all jobs"',
  allFiltersButton: 'text="All filters"',
  showResultsButton: "text=/show \\d+ result(s)?/i",
  showResultsButton2: "Apply current filters to show",
  isHeadless: true,
};

// Filters
const optionalFilters = new Set(["Past week", "Internship", "Canada"]);
const requiredFilters = new Set(["Past 24 hours", "Internship", "Canada"]);

const scrapeBot = new LinkedInScraper(
  __cookie_path,
  optionalFilters,
  requiredFilters,
  SELECTORS,
  process.env.LINKEDIN_MAIL,
  process.env.LINKEDIN_PASSWORD,
  process.env.LINKEDIN_URL
);

const companies1 = [
  "https://www.linkedin.com/company/ada-support/jobs/",
  "https://www.linkedin.com/company/applyboard/jobs/",
  "https://www.linkedin.com/company/wealthsimple/jobs/",
  "https://www.linkedin.com/company/tenstorrent/jobs/",
  "https://www.linkedin.com/company/coinsquare/jobs/",
  "https://www.linkedin.com/company/kepler-communications-inc-/jobs/",
  "https://www.linkedin.com/company/skywatch-space-applications-inc-/jobs/",
  "https://www.linkedin.com/company/wavehq/jobs/",
  "https://www.linkedin.com/company/xanaduai/jobs/",
  "https://www.linkedin.com/company/financeit/jobs/",
  "https://www.linkedin.com/company/wattpad/jobs/",
  "https://www.linkedin.com/company/wombo-ai/jobs/",
  "https://www.linkedin.com/company/partnerstack/jobs/",
  "https://www.linkedin.com/company/leagueinc/jobs/",
  "https://www.linkedin.com/company/freshbooks/jobs/",
  "https://www.linkedin.com/company/vidyard/jobs/",
  "https://www.linkedin.com/company/1password/jobs/",
  "https://www.linkedin.com/company/rocket-doctor-inc-/jobs/",
  "https://www.linkedin.com/company/ecobee/jobs/",
  "https://www.linkedin.com/company/ledninc/jobs/",
  "https://www.linkedin.com/company/knixwear/jobs/",
  "https://www.linkedin.com/company/vena-solutions/jobs/",
  "https://www.linkedin.com/company/ritual-co/jobs/",
  "https://www.linkedin.com/company/avison-young/jobs/",
  "https://www.linkedin.com/company/railz/jobs/",
  "https://www.linkedin.com/company/snapcommerce/jobs/",
  "https://www.linkedin.com/company/tophat/jobs/",
  "https://www.linkedin.com/company/loopio/jobs/",
  "https://www.linkedin.com/company/benchsci/jobs/",
  "https://www.linkedin.com/company/essential-accessibility/jobs/",
  "https://www.linkedin.com/company/koho-financial-inc-/jobs/",
  "https://www.linkedin.com/company/contentfly/jobs/",
  "https://www.linkedin.com/company/relayfi/jobs/",
  "https://www.linkedin.com/company/pointclickcare/jobs/",
  "https://www.linkedin.com/company/bluerocktx/jobs/",
  "https://www.linkedin.com/company/dentalcorp-canada/jobs/",
  "https://www.linkedin.com/company/intelex-technologies-ulo/jobs/",
  "https://www.linkedin.com/company/joinsherpa/jobs/",
  "https://www.linkedin.com/company/earnwithdrop/jobs/",
  "https://www.linkedin.com/company/adeptmind/jobs/",
  "https://www.linkedin.com/company/esentire/jobs/",
  "https://www.linkedin.com/company/mindbridge-ai/jobs/",
  "https://www.linkedin.com/company/cority/jobs/",
  "https://www.linkedin.com/company/nanoleaf/jobs/",
  "https://www.linkedin.com/company/q4-inc-/jobs/",
  "https://www.linkedin.com/company/getmaple/jobs/",
  "https://www.linkedin.com/company/paybright/jobs/",
  "https://www.linkedin.com/company/borrowell/jobs/",
  "https://www.linkedin.com/company/mejuri/jobs/",
  "https://www.linkedin.com/company/choosemuse/jobs/",
  "https://www.linkedin.com/company/sensibill/jobs/",
  "https://www.linkedin.com/company/li-cycle-corp-/jobs/",
  "https://www.linkedin.com/company/axonify/jobs/",
  "https://www.linkedin.com/company/newton-co-/jobs/",
  "https://www.linkedin.com/company/d2l/jobs/",
  "https://www.linkedin.com/company/kira-systems/jobs/",
  "https://www.linkedin.com/company/field-trip-health/jobs/",
  "https://www.linkedin.com/company/miovision/jobs/",
  "https://www.linkedin.com/company/northwear/jobs/",
  "https://www.linkedin.com/company/stackadapt/jobs/",
  "https://www.linkedin.com/company/hellonotch/jobs/",
  "https://www.linkedin.com/company/tread-technologies/jobs/",
  "https://www.linkedin.com/company/uberflip/jobs/",
  "https://www.linkedin.com/company/360insights/jobs/",
  "https://www.linkedin.com/company/nulogy-corporation/jobs/",
  "https://www.linkedin.com/company/igloo-software/jobs/",
  "https://www.linkedin.com/company/clearpathrobotics/jobs/",
  "https://www.linkedin.com/company/flipp/jobs/",
  "https://www.linkedin.com/company/medchart/jobs/",
  "https://www.linkedin.com/company/cyclica/jobs/",
  "https://www.linkedin.com/company/flybits/jobs/",
  "https://www.linkedin.com/company/assent-compliance-inc-/jobs/",
  "https://www.linkedin.com/company/advisorstream/jobs/",
  "https://www.linkedin.com/company/tulip-retail/jobs/",
  "https://www.linkedin.com/company/tealbook/jobs/",
  "https://www.linkedin.com/company/thentia/jobs/",
  "https://www.linkedin.com/company/thriver/jobs/",
  "https://www.linkedin.com/company/joinlane/jobs/",
  "https://www.linkedin.com/company/fiix-software/jobs/",
  "https://www.linkedin.com/company/sourcedgroup/jobs/",
  "https://www.linkedin.com/company/clutchcanada/jobs/",
  "https://www.linkedin.com/company/hostaway/jobs/",
  "https://www.linkedin.com/company/open-farm-pet-food/jobs/",
  "https://www.linkedin.com/company/resolver-inc-/jobs/",
  "https://www.linkedin.com/company/validere/jobs/",
  "https://www.linkedin.com/company/delphia/jobs/",
  "https://www.linkedin.com/company/figure1/jobs/",
  "https://www.linkedin.com/company/humi/jobs/",
  "https://www.linkedin.com/company/dejero/jobs/",
  "https://www.linkedin.com/company/relayplatform/jobs/",
  "https://www.linkedin.com/company/auvik-networks-inc-/jobs/",
  "https://www.linkedin.com/company/swyft/jobs/",
  "https://www.linkedin.com/company/agnostiq/jobs/",
  "https://www.linkedin.com/company/influitive/jobs/",
  "https://www.linkedin.com/company/limelight-platform/jobs/",
  "https://www.linkedin.com/company/tier1crm/jobs/",
  "https://www.linkedin.com/company/avidbots-corp-/jobs/",
  "https://www.linkedin.com/company/rewindio/jobs/",
  "https://www.linkedin.com/company/synaptive-medical/jobs/",
  "https://www.linkedin.com/company/integrate-ai/jobs/",
  "https://www.linkedin.com/company/gansystems/jobs/",
  "https://www.linkedin.com/company/sheertex/jobs/",
  "https://www.linkedin.com/company/untether-ai/jobs/",
  "https://www.linkedin.com/company/ideal-com/jobs/",
  "https://www.linkedin.com/company/flexiti/jobs/",
  "https://www.linkedin.com/company/hashtagpaid/jobs/",
  "https://www.linkedin.com/company/3-commas-technologies-pvt-ltd-/jobs/",
  "https://www.linkedin.com/company/cinchy/jobs/",
  "https://www.linkedin.com/company/blackcart/jobs/",
  "https://www.linkedin.com/company/wondr-gaming/jobs/",
  "https://www.linkedin.com/company/fleetops/jobs/",
  "https://www.linkedin.com/company/bridgitsolutions/jobs/",
  "https://www.linkedin.com/company/plooto/jobs/",
  "https://www.linkedin.com/company/fundthrough/jobs/",
  "https://www.linkedin.com/company/fullscript/jobs/",
  "https://www.linkedin.com/company/darwinai/jobs/",
  "https://www.linkedin.com/company/panorama/jobs/",
  "https://www.linkedin.com/company/statflo/jobs/",
  "https://www.linkedin.com/company/textnow/jobs/",
  "https://www.linkedin.com/company/inkbox-tattoos/jobs/",
  "https://www.linkedin.com/company/fluence-technologies/jobs/",
  "https://www.linkedin.com/company/securekey-technologies-inc-/jobs/",
  "https://www.linkedin.com/company/corvista-health/jobs/",
  "https://www.linkedin.com/company/buyproperly/jobs/",
  "https://www.linkedin.com/company/ilobbycorp/jobs/",
  "https://www.linkedin.com/company/medavail/jobs/",
  "https://www.linkedin.com/company/taplytics/jobs/",
  "https://www.linkedin.com/company/setter/jobs/",
  "https://www.linkedin.com/company/shoplazza/jobs/",
  "https://www.linkedin.com/company/plum-io/jobs/",
  "https://www.linkedin.com/company/bonsai/jobs/",
  "https://www.linkedin.com/company/bluedot-consulting/jobs/",
  "https://www.linkedin.com/company/500px/jobs/",
  "https://www.linkedin.com/company/ethoca/jobs/",
  "https://www.linkedin.com/company/prophix-software/jobs/",
  "https://www.linkedin.com/company/terrestrial-energy-inc-/jobs/",
  "https://www.linkedin.com/company/flow-water-inc-/jobs/",
  "https://www.linkedin.com/company/hydrostor/jobs/",
  "https://www.linkedin.com/company/sproutatwork/jobs/",
  "https://www.linkedin.com/company/peak-power-inc-/jobs/",
  "https://www.linkedin.com/company/chargelab/jobs/",
  "https://www.linkedin.com/company/ross-video/jobs/",
  "https://www.linkedin.com/company/doxim/jobs/",
  "https://www.linkedin.com/company/pathfactory/jobs/",
  "https://www.linkedin.com/company/anaergia-inc-/jobs/",
  "https://www.linkedin.com/company/forma-ai/jobs/",
  "https://www.linkedin.com/company/saltedge/jobs/",
  "https://www.linkedin.com/company/tailscale/jobs/",
  "https://www.linkedin.com/company/pythian/jobs/",
  "https://www.linkedin.com/company/ratehub-ca/jobs/",
  "https://www.linkedin.com/company/nest-wealth/jobs/",
  "https://www.linkedin.com/company/dtrade/jobs/",
  "https://www.linkedin.com/company/quandl/jobs/",
  "https://www.linkedin.com/company/buf-build/jobs/",
  "https://www.linkedin.com/company/energyx/jobs/",
  "https://www.linkedin.com/company/thoughtwire/jobs/",
  "https://www.linkedin.com/company/paystone/jobs/",
  "https://www.linkedin.com/company/upchain-inc-/jobs/",
  "https://www.linkedin.com/company/knowledgehook/jobs/",
  "https://www.linkedin.com/company/swift-medical/jobs/",
  "https://www.linkedin.com/company/solink/jobs/",
  "https://www.linkedin.com/company/trufan/jobs/",
  "https://www.linkedin.com/company/pitstopconnect/jobs/",
  "https://www.linkedin.com/company/himama/jobs/",
  "https://www.linkedin.com/company/canvass-analytics-inc-/jobs/",
  "https://www.linkedin.com/company/movesfinancial/jobs/",
  "https://www.linkedin.com/company/nudge-ai/jobs/",
  "https://www.linkedin.com/company/coinsmart/jobs/",
  "https://www.linkedin.com/company/nymi/jobs/",
  "https://www.linkedin.com/company/jiffyondemand/jobs/",
  "https://www.linkedin.com/company/caary-capital/jobs/",
  "https://www.linkedin.com/company/scribblelive/jobs/",
  "https://www.linkedin.com/company/buckzy-payments/jobs/",
  "https://www.linkedin.com/company/amp/jobs/",
  "https://www.linkedin.com/company/aya-fm/jobs/",
  "https://www.linkedin.com/company/joist-app/jobs/",
  "https://www.linkedin.com/company/nanology-labs/jobs/",
  "https://www.linkedin.com/company/flashfood/jobs/",
  "https://www.linkedin.com/company/umbra/jobs/",
  "https://www.linkedin.com/company/nicoyalife/jobs/",
  "https://www.linkedin.com/company/elocitytech/jobs/",
  "https://www.linkedin.com/company/bluejlegal/jobs/",
  "https://www.linkedin.com/company/ecopia-tech/jobs/",
  "https://www.linkedin.com/company/crowdriff/jobs/",
  "https://www.linkedin.com/company/voices-com/jobs/",
  "https://www.linkedin.com/company/blueprint-software-systems/jobs/",
  "https://www.linkedin.com/company/notch-therapeutics/jobs/",
  "https://www.linkedin.com/company/planswell/jobs/",
  "https://www.linkedin.com/company/providence-therapeutics/jobs/",
  "https://www.linkedin.com/company/klipfolio/jobs/",
  "https://www.linkedin.com/company/boosted-ai/jobs/",
  "https://www.linkedin.com/company/nanopay/jobs/",
  "https://www.linkedin.com/company/daisy-intelligence-corporation/jobs/",
  "https://www.linkedin.com/company/roadmunk/jobs/",
  "https://www.linkedin.com/company/synapsemx/jobs/",
  "https://www.linkedin.com/company/intellijoint-surgical-inc-/jobs/",
  "https://www.linkedin.com/company/varagesale/jobs/",
  "https://www.linkedin.com/company/rubikloud/jobs/",
  "https://www.linkedin.com/company/artboard-studio/jobs/",
  "https://www.linkedin.com/company/phenomic-ai/jobs/",
  "https://www.linkedin.com/company/autoleap/jobs/",
  "https://www.linkedin.com/company/disco-xyz/jobs/",
  "https://www.linkedin.com/company/encycle-corporation/jobs/",
  "https://www.linkedin.com/company/careguide/jobs/",
  "https://www.linkedin.com/company/oncallhealth/jobs/",
  "https://www.linkedin.com/company/orchard-app/jobs/",
  "https://www.linkedin.com/company/ruckify/jobs/",
  "https://www.linkedin.com/company/overactive-media-group/jobs/",
  "https://www.linkedin.com/company/goodlife-fitness/jobs/",
  "https://www.linkedin.com/company/tryvantage/jobs/",
  "https://www.linkedin.com/company/invixium/jobs/",
  "https://www.linkedin.com/company/corsa-security/jobs/",
  "https://www.linkedin.com/company/tehama/jobs/",
  "https://www.linkedin.com/company/proteinqure/jobs/",
  "https://www.linkedin.com/company/dozr/jobs/",
  "https://www.linkedin.com/company/heirlume/jobs/",
  "https://www.linkedin.com/company/endy-/jobs/",
  "https://www.linkedin.com/company/convictional/jobs/",
  "https://www.linkedin.com/company/bonfireinteractive/jobs/",
  "https://www.linkedin.com/company/knockri/jobs/",
  "https://www.linkedin.com/company/odaia-intelligence/jobs/",
  "https://www.linkedin.com/company/winterlight-labs/jobs/",
  "https://www.linkedin.com/company/lifelabs-medical-laboratory-services/jobs/",
  "https://www.linkedin.com/company/chef-s-plate/jobs/",
  "https://www.linkedin.com/company/gbatteries/jobs/",
  "https://www.linkedin.com/company/blackberryqnx/jobs/",
  "https://www.linkedin.com/company/geneseeq/jobs/",
  "https://www.linkedin.com/company/peraso-technologies-inc-/jobs/",
  "https://www.linkedin.com/company/thinkdataworks/jobs/",
  "https://www.linkedin.com/company/tyltgo/jobs/",
  "https://www.linkedin.com/company/myant/jobs/",
  "https://www.linkedin.com/company/dlt-labs/jobs/",
  "https://www.linkedin.com/company/vive-crop-protection/jobs/",
  "https://www.linkedin.com/company/ironshore-pharmaceuticals-&-development,-inc-/jobs/",
  "https://www.linkedin.com/company/noblegen-inc-/jobs/",
  "https://www.linkedin.com/company/seamless-mobile-health/jobs/",
  "https://www.linkedin.com/company/resemble-ai/jobs/",
];
const companies2 = [
    "https://www.linkedin.com/company/general-motors/jobs/", 
    "https://www.linkedin.com/company/honeywell/jobs/", 
    "https://www.linkedin.com/company/amazon/jobs/",
    "https://www.linkedin.com/company/huawei/jobs/",
    "https://www.linkedin.com/company/ansys-inc/jobs/",
    "https://www.linkedin.com/company/electronic-arts/jobs/",
    "https://www.linkedin.com/company/ibm/jobs/",
    "https://www.linkedin.com/company/intel-corporation/jobs/",
    "https://www.linkedin.com/company/samsung-electronics/jobs/",
    "https://www.linkedin.com/company/facebook/jobs/",
    "https://www.linkedin.com/company/netflix/jobs/",
    "https://www.linkedin.com/company/adobe/jobs/",
    "https://www.linkedin.com/company/tesla-motors/jobs/",
    "https://www.linkedin.com/company/nvidia/jobs/",
    "https://www.linkedin.com/company/spotify/jobs/",
    "https://www.linkedin.com/company/salesforce/jobs/",
    "https://www.linkedin.com/company/shopify/jobs/",
    "https://www.linkedin.com/company/dell-technologies/jobs/",
    "https://www.linkedin.com/company/siemens/jobs/",
    "https://www.linkedin.com/company/sap/jobs/",
    "https://www.linkedin.com/company/oracle/jobs/",
    "https://www.linkedin.com/company/paypal/jobs/",
    "https://www.linkedin.com/company/airbnb/jobs/",
    "https://www.linkedin.com/company/dropbox/jobs/",
    "https://www.linkedin.com/company/twitter/jobs/",
    "https://www.linkedin.com/company/slack-technologies/jobs/",
    "https://www.linkedin.com/company/hpe/jobs/",
    "https://www.linkedin.com/company/zoho/jobs/",
    "https://www.linkedin.com/company/snap-inc/jobs/",
    "https://www.linkedin.com/company/atlassian/jobs/",
    "https://www.linkedin.com/company/uber/jobs/",
    "https://www.linkedin.com/company/doordash/jobs/",
    "https://www.linkedin.com/company/lyft/jobs/"
  ];
  
await scrapeBot.setUp();
const currentTime = new Date();
console.log(currentTime.toString());

for (const company of companies2) {
    console.log(company)
  const jobsFound = await scrapeBot.browse(company);
  console.log(`${jobsFound.length} found`);
  console.log(jobsFound);
}

console.log(currentTime.toString());

scrapeBot.cleanUp();
