import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.linkedin.com/');
  await page.locator('[data-test-id="home-hero-sign-in-cta"]').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Ma');
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('');
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Toan2002@');
  await page.getByLabel('Sign in', { exact: true }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.locator('iframe[title="Sign in with Google Button"]').contentFrame().getByLabel('Continue with Google').click();
  const page1 = await page1Promise;
  await page1.getByLabel('Email or phone').click();
  await page1.getByLabel('Email or phone').fill('bachmatoan2910@gmail.com');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByLabel('Try again').click();
  await page1.getByLabel('Email or phone').click();
  await page1.getByLabel('Email or phone').click();
  await page.getByLabel('Email or phone').dblclick();
  await page.getByLabel('Email or phone').dblclick();
  await page.getByLabel('Email or phone').fill('@gmail.com');
  await page.getByLabel('Email or phone').press('ControlOrMeta+ArrowRight');
  await page.getByLabel('Email or phone').fill('4372232812');
  await page.getByLabel('Email or phone').press('ControlOrMeta+ArrowLeft');
  await page.getByLabel('Email or phone').fill('4372232812');
  await page.getByLabel('Email or phone').press('ArrowDown');
  await page.getByLabel('Email or phone').press('ArrowDown');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Toan2--2@');
  await page.getByLabel('Sign in').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Toann2002@');
  await page.getByLabel('Sign in').click();
  await page.getByLabel('Email or phone').click();
  await page.getByLabel('Email or phone').dblclick();
  await page.getByLabel('Email or phone').dblclick();
  await page.getByLabel('Email or phone').fill('bacj1 4372232812');
  await page.getByLabel('Email or phone').press('ControlOrMeta+Shift+ArrowRight');
  await page.getByLabel('Email or phone').fill('bachmatoan2910@gmail.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Toan2002@');
  await page.getByLabel('Sign in').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').press('CapsLock');
  await page.getByLabel('Password').fill('Toan2002@');
  await page.getByLabel('Sign in').click();
  await page.getByPlaceholder('Search', { exact: true }).press('CapsLock');
  await page.getByPlaceholder('Search', { exact: true }).fill('Software');
  await page.locator('#basic-result-4kusts div').filter({ hasText: 'software engineer intern' }).click();
  await page.getByRole('link', { name: 'See all job results in Canada', exact: true }).click();
});